### ISSUE TITLE
Errors out with EAFNOSUPPORT

### ISSUE THREAD

**Issue by petefirefox** [oyooyo/keyble#26]
Hello,

I'm very interested in using keyble for my equiva EQ3 smart lock.
Unfortunately I get below error every time that I try to run the user registration:

keyble-registeruser -n xyz -q MxyzMxyz
/usr/lib/node_modules/keyble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:74
  this._socket = new BluetoothHciSocket();
                 ^

Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/usr/lib/node_modules/keyble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:74:18)
    at new NobleBindings (/usr/lib/node_modules/keyble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
    at Object.<anonymous> (/usr/lib/node_modules/keyble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:546:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (/usr/lib/node_modules/keyble/node_modules/@abandonware/noble/lib/resolve-bindings.js:13:12) {
  errno: 97,
  code: 'EAFNOSUPPORT',
  syscall: 'socket'
}

It appears to be some version inconsistency with noble. I already searched the internet heavily, did try to build with different versions of node, but no success.

Do you have any hints on how I could this successful to build and run?

Thanks a lot in advance.

Peter

**Comment by petefirefox** [comment]
Problem got solved by a reboot. Strange, but ok.
Also I had the problem that the RPI 3 internal BT module does not work reliable.
I did now put a USB BT BLE 4.0 dongle in and everything works like a charm.
